#!/bin/bash

BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${BUILD_SCRIPTS_DIR}"/git-hooks-commons

# shellcheck disable=SC2154
if [ ! -d "$hooks_dir" ]; then
  mkdir -p "$hooks_dir"
fi

cp -i "${BUILD_SCRIPTS_DIR}"/hooks/* "${hooks_dir}"
# shellcheck disable=SC2154
git config --global init.templateDir "${templates_dir}"
